import "./components/lang";
import "./components/swiper";
import "./components/modal";
import "./components/labels";
import "./components/table";
import "./components/partner-animation";
import "./components/burger";
import "./components/dynamic-adapt";
import "./components/custom-scroll";
